import { readFile, writeFile, mkdir } from 'fs/promises';
import { existsSync } from 'fs';
import { join } from 'path';
import { mutateOpencodeConfig } from './opencode-config.js';
import { resolveScope, defaultScope, assertValidPluginId, type InstallScope } from './scope.js';

/**
 * Upper bound on a CC hook matcher length. Matchers go into a generated
 * `new RegExp(...)` inside the shim, so an attacker plugin could embed a
 * pathological pattern (e.g. nested quantifiers) and stall every tool call
 * with catastrophic backtracking. Real CC matchers are short tool names
 * (`Bash`, `Edit`, `Edit|Write`); 200 chars is generous.
 */
const MAX_MATCHER_LENGTH = 200;

export interface TranslateHooksOptions {
  scope?: InstallScope;
}

type CcHookMatcher = {
  matcher?: string;
  hooks: Array<{ type: string; command?: string }>;
};

/**
 * Translate CC `hooks.PreToolUse` / `hooks.PostToolUse` → an ESM OpenCode
 * plugin shim that wraps each bash command via `child_process.spawn`.
 * Registers `file://<shim>` in scope's `opencode.json plugin[]`.
 * Other CC hook events get a warning and are skipped.
 */
export async function translateHooks(
  installPath: string,
  pluginId: string,
  opts?: TranslateHooksOptions,
): Promise<string[]> {
  assertValidPluginId(pluginId);

  const manifestPath = join(installPath, '.claude-plugin', 'plugin.json');
  if (!existsSync(manifestPath)) return [];

  const manifest = JSON.parse(await readFile(manifestPath, 'utf-8')) as {
    hooks?: Record<string, CcHookMatcher[]>;
  };
  const ccHooks = manifest.hooks ?? {};
  if (Object.keys(ccHooks).length === 0) return [];

  const preToolUse: Array<{ matcher: string; command: string }> = [];
  const postToolUse: Array<{ matcher: string; command: string }> = [];

  for (const [event, matchers] of Object.entries(ccHooks)) {
    if (event !== 'PreToolUse' && event !== 'PostToolUse') {
      console.warn(`[plugger] hook event "${event}" in ${pluginId} is not supported by OpenCode — skipping`);
      continue;
    }
    const bucket = event === 'PreToolUse' ? preToolUse : postToolUse;
    for (const m of matchers) {
      let matcher = m.matcher ?? '*';
      if (matcher.length > MAX_MATCHER_LENGTH) {
        console.warn(`[plugger] matcher in ${pluginId} exceeds ${MAX_MATCHER_LENGTH} chars — coercing to no-op '*' to avoid ReDoS`);
        matcher = '*';
      }
      for (const h of m.hooks) {
        if (h.type !== 'command' || !h.command) continue;
        bucket.push({ matcher, command: h.command });
      }
    }
  }

  if (preToolUse.length === 0 && postToolUse.length === 0) return [];

  const paths = resolveScope(opts?.scope ?? defaultScope());
  await mkdir(paths.hookShimsDir, { recursive: true });
  await writeFile(join(paths.hookShimsDir, 'package.json'), '{"type":"module"}\n', 'utf-8');

  const shimPath = join(paths.hookShimsDir, `${pluginId}.js`);
  await writeFile(shimPath, renderShim(pluginId, preToolUse, postToolUse), 'utf-8');

  const pluginEntry = `file://${shimPath}`;
  await mutateOpencodeConfig((cfg) => {
    cfg.plugin ??= [];
    if (!cfg.plugin.some((p) => p === pluginEntry)) {
      cfg.plugin.push(pluginEntry);
    }
  }, paths.opencodeConfigPath);

  return [shimPath];
}

function renderShim(
  pluginId: string,
  pre: Array<{ matcher: string; command: string }>,
  post: Array<{ matcher: string; command: string }>,
): string {
  const payload = JSON.stringify({ pluginId, pre, post }, null, 2);
  return `// auto-generated by plugger-open-code translator — do not edit
import { spawn } from 'node:child_process';

const HOOKS = ${payload};

function matchTool(matcher, tool) {
  if (!matcher || matcher === '*') return true;
  try { return new RegExp('^(?:' + matcher + ')$').test(tool); }
  catch { return false; }
}

function runCommand(command, ctx) {
  return new Promise((resolve) => {
    const child = spawn('bash', ['-c', command], { stdio: ['pipe', 'pipe', 'pipe'] });
    child.stdin.end(JSON.stringify(ctx));
    let err = '';
    child.stderr.on('data', (d) => { err += d.toString(); });
    child.on('close', (code) => {
      if (code !== 0) {
        console.error('[plugger hook ' + HOOKS.pluginId + '] exit ' + code + ': ' + err.trim());
      }
      resolve();
    });
    child.on('error', (e) => {
      console.error('[plugger hook ' + HOOKS.pluginId + '] spawn error: ' + e.message);
      resolve();
    });
  });
}

export default async function () {
  return {
    'tool.execute.before': async (input) => {
      for (const entry of HOOKS.pre) {
        if (matchTool(entry.matcher, input.tool)) {
          await runCommand(entry.command, {
            hook_event_name: 'PreToolUse',
            tool_name: input.tool,
            session_id: input.sessionID,
          });
        }
      }
    },
    'tool.execute.after': async (input) => {
      for (const entry of HOOKS.post) {
        if (matchTool(entry.matcher, input.tool)) {
          await runCommand(entry.command, {
            hook_event_name: 'PostToolUse',
            tool_name: input.tool,
            session_id: input.sessionID,
          });
        }
      }
    },
  };
}
`;
}
